# This workflow will install Python and run readme_generator.py

name: Update README.md

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run readme_generator.py 
      run: |
        python3 readme_generator.py > README.md
        python3 readme_generator.py
    - name: Commit Changes
      run: |
        git config --global user.name 'BrandonTang89'
        git config --global user.email 'BrandonTang89@users.noreply.github.com'
        git commit -am "Updated README.md"
        git push
        
